// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4P5zM3EH5HOeahNbzzjcX9jquodveRQ',
    appId: '1:215101057073:web:51e10ecbc8a67ce4900d10',
    messagingSenderId: '215101057073',
    projectId: 'vidhishayak',
    authDomain: 'vidhishayak.firebaseapp.com',
    storageBucket: 'vidhishayak.firebasestorage.app',
    measurementId: 'G-FR5YPC1TL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPU6E4tL3QZlx3BpOeQyw5guNFwwt51g',
    appId: '1:796021876250:android:d6e9ee53f05e53c8d193a3',
    messagingSenderId: '796021876250',
    projectId: 'vidhishayak-e4abb',
    storageBucket: 'vidhishayak-e4abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZN3QZQrHbd436LGuLmJcqqqn0mJGwzH4',
    appId: '1:796021876250:ios:fa15b24ed4cfa1d8d193a3',
    messagingSenderId: '796021876250',
    projectId: 'vidhishayak-e4abb',
    storageBucket: 'vidhishayak-e4abb.firebasestorage.app',
    iosClientId: '796021876250-gnp2lumgo5o4uncdtbkbaq5r45tvhnn6.apps.googleusercontent.com',
    iosBundleId: 'com.kitm.vidhishayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPzOuuYNSfaGaydUdVW2OQG-0C_tCqPKM',
    appId: '1:215101057073:ios:6e2d2df2d423cd41900d10',
    messagingSenderId: '215101057073',
    projectId: 'vidhishayak',
    storageBucket: 'vidhishayak.firebasestorage.app',
    androidClientId: '215101057073-4nc9ljt3d4k16oklm0e3em3sb5srk8gd.apps.googleusercontent.com',
    iosClientId: '215101057073-4jckb9q9accbejkn6ia7hoburdunc3hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vidhiShayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn4P5zM3EH5HOeahNbzzjcX9jquodveRQ',
    appId: '1:215101057073:web:40daf5c6cfc8238c900d10',
    messagingSenderId: '215101057073',
    projectId: 'vidhishayak',
    authDomain: 'vidhishayak.firebaseapp.com',
    storageBucket: 'vidhishayak.firebasestorage.app',
    measurementId: 'G-0PVBJL59NY',
  );

}